import type { Db } from './db.ts'
import type { TemplateRow } from './types.ts'
type Row = Record<string, any>
const toTemplate = (r: Row): TemplateRow => ({ metaTemplateId: r.meta_template_id, wabaId: r.waba_id, name: r.name, language: r.language, category: r.category, status: r.status, parameterFormat: r.parameter_format, components: JSON.parse(r.components), definition: JSON.parse(r.definition_json ?? '{}'), generation: r.generation ?? 1, rejectionReason: r.rejection_reason ?? undefined, createdAt: r.created_at, updatedAt: r.updated_at })
export function insertTemplate(db: Db, t: TemplateRow): void { db.prepare('INSERT INTO template (meta_template_id, waba_id, name, language, category, status, parameter_format, components, definition_json, generation, rejection_reason, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)').run(t.metaTemplateId, t.wabaId, t.name, t.language, t.category, t.status, t.parameterFormat, JSON.stringify(t.components), JSON.stringify(t.definition ?? {}), t.generation ?? 1, t.rejectionReason ?? null, t.createdAt, t.updatedAt) }
export function getTemplateById(db: Db, id: string): TemplateRow | undefined { const r = db.prepare('SELECT * FROM template WHERE meta_template_id = ?').get(id) as Row | undefined; return r ? toTemplate(r) : undefined }
export function findTemplate(db: Db, wabaId: string, name: string, language: string): TemplateRow | undefined { const r = db.prepare('SELECT * FROM template WHERE waba_id = ? AND name = ? AND language = ?').get(wabaId, name, language) as Row | undefined; return r ? toTemplate(r) : undefined }
export function listTemplates(db: Db, wabaId?: string): TemplateRow[] { const rows = wabaId ? db.prepare('SELECT * FROM template WHERE waba_id = ? ORDER BY name, language').all(wabaId) : db.prepare('SELECT * FROM template ORDER BY waba_id, name, language').all(); return (rows as Row[]).map(toTemplate) }
export function listTemplatesByName(db: Db, wabaId: string, name: string): TemplateRow[] { return (db.prepare('SELECT * FROM template WHERE waba_id = ? AND name = ? ORDER BY language').all(wabaId, name) as Row[]).map(toTemplate) }
export function updateTemplate(db: Db, t: TemplateRow): void { db.prepare('UPDATE template SET category = ?, status = ?, parameter_format = ?, components = ?, definition_json = ?, generation = ?, rejection_reason = NULL, updated_at = ? WHERE meta_template_id = ?').run(t.category, t.status, t.parameterFormat, JSON.stringify(t.components), JSON.stringify(t.definition ?? {}), t.generation ?? 1, t.updatedAt, t.metaTemplateId) }
export function setTemplateStatus(db: Db, id: string, status: string, at: number, generation: number, reason?: string): void {
  const result = db.prepare('UPDATE template SET status = ?, rejection_reason = ?, updated_at = ? WHERE meta_template_id = ? AND generation = ?').run(status, reason ?? null, at, id, generation)
  if (Number(result.changes) !== 1) throw new Error(`template ${id} has changed; refresh before applying a decision`)
}
export function deleteTemplate(db: Db, id: string): void { db.prepare('DELETE FROM template WHERE meta_template_id = ?').run(id) }
export function listPendingTemplates(db: Db): TemplateRow[] { return (db.prepare("SELECT * FROM template WHERE status = 'PENDING'").all() as Row[]).map(toTemplate) }
